# Generated by Django 3.2.16 on 2022-12-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='field_of_study',
            new_name='fieldofstudy',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='studentnumber',
        ),
    ]
